# Generated by Django 2.2.6 on 2019-10-09 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('fabricante', models.CharField(max_length=256)),
                ('info', models.CharField(blank=True, max_length=512)),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_produto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('info', models.CharField(blank=True, max_length=512)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('tempo_estimado', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produtos_utilizados', models.ManyToManyField(blank=True, to='pets.Produto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_servico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrocaDePreco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alterado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('antigo_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('novo_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='pets.Servico')),
            ],
        ),
        migrations.CreateModel(
            name='FluxoDeEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('qunatidade_anterior', models.PositiveIntegerField()),
                ('qunatidade_posterior', models.PositiveIntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='pets.Produto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fluxo_de_estoque', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
