# Generated by Django 2.2.6 on 2019-10-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_servicoregistro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxodeestoque',
            old_name='qunatidade_anterior',
            new_name='quantidade_anterior',
        ),
        migrations.RenameField(
            model_name='fluxodeestoque',
            old_name='qunatidade_posterior',
            new_name='quantidade_posterior',
        ),
    ]
