# Generated by Django 2.2.6 on 2019-10-10 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0004_auto_20191010_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(default=django.utils.timezone.now)),
                ('nome_do_cliente', models.CharField(max_length=256)),
                ('email_do_cliente', models.EmailField(max_length=254)),
                ('profissionais', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notificacao', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao_servico', to='pets.Servico')),
            ],
        ),
    ]
