# Generated by Django 2.2.6 on 2019-10-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cliente'), (2, 'Atendente'), (3, 'Veterinário'), (4, 'Administrador')], default=1),
        ),
    ]
